name: hassen_entertainment_automation
description: "A new Flutter project for Hotel Automation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  file_picker: ^8.0.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.5
  lottie: ^3.1.2
  audio_video_progress_bar: ^2.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # تعريف المجلدات الخاصة بالـ Assets
  assets:
    - assets/lottie/